version: '3.7'

services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gympass
  app: 
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

